
package SupportService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SupportWsdlService", targetNamespace = "Support", wsdlLocation = "http://localhost:5924/support?wsdl")
public class SupportWsdlService
    extends Service
{

    private final static URL SUPPORTWSDLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUPPORTWSDLSERVICE_EXCEPTION;
    private final static QName SUPPORTWSDLSERVICE_QNAME = new QName("Support", "SupportWsdlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5924/support?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUPPORTWSDLSERVICE_WSDL_LOCATION = url;
        SUPPORTWSDLSERVICE_EXCEPTION = e;
    }

    public SupportWsdlService() {
        super(__getWsdlLocation(), SUPPORTWSDLSERVICE_QNAME);
    }

    public SupportWsdlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUPPORTWSDLSERVICE_QNAME, features);
    }

    public SupportWsdlService(URL wsdlLocation) {
        super(wsdlLocation, SUPPORTWSDLSERVICE_QNAME);
    }

    public SupportWsdlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUPPORTWSDLSERVICE_QNAME, features);
    }

    public SupportWsdlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SupportWsdlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SupportWsdl
     */
    @WebEndpoint(name = "SupportWsdlPort")
    public SupportWsdl getSupportWsdlPort() {
        return super.getPort(new QName("Support", "SupportWsdlPort"), SupportWsdl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SupportWsdl
     */
    @WebEndpoint(name = "SupportWsdlPort")
    public SupportWsdl getSupportWsdlPort(WebServiceFeature... features) {
        return super.getPort(new QName("Support", "SupportWsdlPort"), SupportWsdl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUPPORTWSDLSERVICE_EXCEPTION!= null) {
            throw SUPPORTWSDLSERVICE_EXCEPTION;
        }
        return SUPPORTWSDLSERVICE_WSDL_LOCATION;
    }

}
